### ISSUE TITLE
ACE 0.9.33 released 

### ISSUE THREAD

**Issue by arademaker** [dantiston/homebrew-delphin#4]
http://sweaglesw.org/linguistics/ace/

can you update the formula?

**Comment by dantiston** [comment]
@arademaker sorry, just realized where this was, now. This repo has been migrated to the [delph-in organization](https://github.com/delph-in/homebrew-delphin ) and I updated it to support many ACE versions last month, including the latest 0.9.34. [Here is the commit in the delph-in organization](https://github.com/delph-in/homebrew-delphin/commit/d9ca545177e1e15be39aebed370d572310fdc877#diff-b319910e7f7cdb624e00490ca11f0c5b0b35069a86d3b285467a86e06389c0f4).
